// <auto-generated />
namespace UnitTestResultsImporter.Console.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SelfReferenced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SelfReferenced));
        
        string IMigrationMetadata.Id
        {
            get { return "201210231513149_SelfReferenced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
