// <auto-generated />
namespace GridSpike.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBasicPropertiesToQueuedTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBasicPropertiesToQueuedTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201212061518382_AddBasicPropertiesToQueuedTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
