// <auto-generated />
namespace ModelTest.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DontKnow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DontKnow));
        
        string IMigrationMetadata.Id
        {
            get { return "201209111925195_DontKnow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
