// <auto-generated />
namespace ModelTest.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MakeNameAndEmailAddressNotRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeNameAndEmailAddressNotRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201209111934276_MakeNameAndEmailAddressNotRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
