// <auto-generated />
namespace SelfReference.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207031318046_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9d5ef4qP89rQjMffzefjOWdj9LjssgaafCeyO08BHIf2W6p41NCsL1+c73KufPPPjpdrMrqOs/9VtTu98qvgw/oo5d1tcrr9pqw1HfPZh+ld8P37nZftK9576B7+m3Z3tv7KH2xLstsUtIH51nZ5B+lq08fvW6rOv88X+Z11uazl1nb5vUS7+aMvpLh0erT21Hi4d2dPVDibrZcVm3W0lz3EO+g+ayomxa/GmxftzXxzkfps+JdPnueLy/aucX4i+yd+YR+/Sj9alkQq9FLbb3O/RHK35t7fp79HHV8usiK8ng2q/Om+dnv/EV2WVzwVHTQ+CJbZhd5/VH6Ki/5+2ZerIT9x4ZZf3/b6FldLV5VJaMffvf7v67W9RRkrAYavMnqi7wNMXt810mI//Fx01TTgvHpCI7FJRzf6XKW3oSYkNgfGFF1XbbFqiymhMRnH32rR7cNcM14bgF3Zzze7Q7cG2JfY5Aqa7OCBFJHTwoKH+Xv2t640fx13nbIRCzlKNvDrjNID5U+JDf5XrMhBukqsVtMix1BgHyI4e0m4jaQArpT0wgvWto7+3FXDIgxNHcHLM3jL7LVigTYszz6SfpazM7J9uv3NyoLgXF32kRsi8XW9kTKnMjS+Za6JkxZzT7N2mySQaWczBa9Zjdzmumoy3D9GTP8Z97A7/LWkPl1PNqB5kj5jEa3IMPEA9VhBnPefzWFB5CVWR0xjidVuV4shwzsprc9m+UD8T6+PSxnhXxQ7tPbQwrNig8t/KYP8fHdDoW7E+rpam3ZEa0ui2zSMnEucsrmPXjFvXRbloA26dEtrlX6ZLoVKxkoMZYCoWz3XwMz1ZxfE7P3xojUwaxgS3zWwMuwHsntxtvVuH3e6CnebhPLmVYBdxTtY1V6N/v9PS0oTT5KafSXxQwa8PV10+aLMRqMX/+i8qQsSBZcAxppcZ437ZvqbY4YZmfn/tcPGqyr3DSz8v+tkUOB4d8YI/QCi/f0+JeXWT2dZ/XWInt350Z/9gYv/oOAxTzzDwLoC4dH0k1AfhYd46/psUZhCcPfAl7fs1aV3hZZSYLftDWJfs/kvKR4aFqssrI7hr7yuw3Xg64WZPebp/kqX4KdY2O8TX+bdb4F35HDm+jwnpFC383rzmE8YNgYL4iS/Oyj2aSi2RaeHXaxf5jhRNTrv1X4IKx7i7e/mZChb6Fo6tcuf0Xs1xQXDgTM7jKfBpNu25wtzyvDfx2MTJOuCsrbbEYccVy3xXk2benrKak3zjb8ZFaumTCTfHa2/HLdrtYtDTlfTMprnxjg4U39c1wU4vz4yxXnFL6JIRCaBQ0h/3L5ZF2UM4v3s765GQIB4VAbhrlsYcsuri2kF9XyloCUfE+NTL/JiXkIWPPl8nV2mQ/jdjMNQ4o9flpkF3W28CkonygmrzPq2euCOvDfcP3Rn8SulDw9+n8CAAD//3ADwpyxFQAA"; }
        }
    }
}
