// <auto-generated />
namespace migration_rnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208141300495_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so0VxUWctYfH718vZR+lxWWSExOu8PH9PjHYeAqOPbF/U2ylh1V6/uV7l3ONnH31x/WZOlPAbUbPfK78OPqCPXtbVKq/b61f5ub56RsjdDd+7233Rvua9g97pt2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mRMZ8tnLrG3zeol3c8ZeqfBo9entCPHw7s4eCHE3Wy6rlikbIv74riNLn1g0dW1WEDKGYmZ63uRNiy/zd22HfPLi67wNidx8lLqOZEbHhv5RhGzXjl3uCr8Yvro7wFiPv8hWK3Tp3tRP0tfCZSfbr9+fnRYC4+60iXCVxdb2RPOYXeSdb6lrwvRZUTft06zNJhlm/WS26DV7H0KbLjv07jKxI795Ab/LS4HY2XnpQHB0fEZDWxBD8ih1jITIgETpu6+nWZnVEZk4qcr1YjkkV/zu3U7H3bF5TKwtO7LZJdYmhus2sb1bxusw2GOd7JvVW2/2pclHKZHlsphh5l9fN22+GKPB+PUvKk/KgsbrGnyRLYtz4ok31dscqnpn5/7XV5NWOzTNrPx/qa4sMPobtWJPlX59HdeX0FspuE36TWb5s49mk4qGJXg6vfg1tV+f6R7f9S3v46d5U1w4ELDDy3wKKXdATZuz5XllpoCG5mNkmnRm6Iu8zWZEoeO6Lc6zaUtfT/Om4fH+ZFauqcnpYpLPzpZfrtvVuj1umnwxKa/98T6+u7l/VvEhzo+/XOEvT8q+/hAIzYKGkH+5fLIuypnF+1mEhQZAgFmULwmr1y348+LaQnpRLW8JSMn3NF/lS3D1m3yxKglY8+XydXaZD+N2Mw1Dij1+WmSk7Bc+BeUTxeR1Rj17XVAH/huuP/qT2JXcvqP/JwAA//8+G5dEawoAAA=="; }
        }
    }
}
