// <auto-generated />
namespace migration_rnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class RenamedNameToFirstName : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208141305105_RenamedNameToFirstName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so0VxUWctYfH718vZR+lxWWSExOu8PH9PjHYeAqOPbF/U2ylh1V6/uV7l3ONnH31x/WZOlPAbUbPfK78OPqCPXtbVKq/b61f5ub56RsjdDd+7233Rvua9g97pt2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mRMZ8tnLrG3zeol3c8ZeqfBo9entCPHw7s4eCHE3Wy6rlinbQ7yD5rOiblr8arB93dagUvqseJfPnufLi3ZuMf4ie2c+oV8/Sr9aFsRe9FJbr3N/hPK33/Pju25C+tNETNNmBZHBzJVhjDd50+LL/F3bmTh58XXehtPbfJS6joSXxmbmowjZrh2j3hVONRx9d4ClH3+RrVbo0r2pn6Svhb9Ptl+/PyMvBMbdaRPhZ4ut7Yk4KLvIO99S14Qpz+3TrM0mGWbvZLboNXsfQpsuO/Tuio8jv3kBv8tLgcDbeelAcHR8RkNbkCjwKHWMhMiALOu7r6dZmdURaTypyvViOSTRm972hMQH4n3ch/X4bmcQXTp5AqEtOxqmS/hNzNttYnu3TNxh1sfKODcr6R4nSZOPUiLSZTEDF72+btp8MUaD8etfVJ6UBY3XNfgiWxbnxF9vqrc5DM7Ozv2vr+ytjmuaWfn/Uo1fYPQ36vaeQXhPTb28zOrpPKu3Ftm7O9+k9u3rjlup3k2aV3jms49mk4rQFzSdxv6aernPwo/v+t7I46d5U1w4EPBNlvkU+scBNW3OlueVoTgNzcfINOlMyBd5m82IQsd1W5xn05a+nuZNw+P9yaxcU5PTxSSfnS2/XLerdXvcNPliUl774318d3P/bHxCnB9/ucJfnsx+/SEQmgUNIf9y+WRdlDOL97M+Qw6BALMolxNW5D0QuItrC+lFtbwlICXf03yVLyEjb/LFqiRgzZfL19llPozbzTQMKfb4aZGRGVr4FJRPFJPXGfXsdUEd+G+4/uhPYldyhY/+nwAAAP//+wL2uX8LAAA="; }
        }
    }
}
