// <auto-generated />
namespace migration_rnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class ChangedStuff : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208141308276_ChangedStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so0VxUWctYfH718vZR+lxWWSExOu8PH9PjHYeAqOPbF/U2ylh1V6/uV7l3ONnH31x/WZOlPAbUbPfK78OPqCPXtbVKq/b61f5ub56RsjdDd+7233Rvua9g97pt2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mRMZ8tnLrG3zeol3c8ZeqfBo9entCPHw7s4eCHE3Wy6rlinbQ7yD5rOiblr8arB93dagUvqseJfPnufLi3ZuMf4ie2c+oV8/Sr9aFsRe9FJbr/PICDd3fVLnGPVT+sd0jt/fFEDGwRLYPqjHd93k9qecGLDNCiKpmXfDZG/ypsWX+bu2wwTy4uu8DVml+Sh1HQlfjg0XRRGyXTumvytcb6Tj7oB4PP4iW63QpXtTP0lfi6ycbL9+f6FYCIy70yYiGxZb2xNxY3aRd76lrglT5hOanmySYWZPZotes/chtOmyQ++uKDrymxfwu7wUKA87Lx0Ijo7PaGgLEisepY6REBnQC/ru62lWZnVEsk+qcr1YDmmHTW97AucD8T6+PaxAgnxowRd9eI/vdojSpbsnYNqyo/26E7lJGLpNbO9WKDrM/1gZ8WYD0uNMafJRSoS6LGbgytfXTZsvxmgwfv2LypOyoPG6Bl9ky+Kc+PVN9TaHMdzZuf/1DZHVv00zK/9fao0KjP5Gu/OeqrxnRZaXWT2dZ/XWInt3573BRSzDjH6Hm/FNWoa+XruVWdhkFYT/CN1JRZgLms6afE2b0ReHx3d9r+vx07wpLhwI+GDLfArd6ICaNmfL88qQm4bmY2SadGbji7zNiPzZcd0W59m0pa+nedPweH8yK9fU5HQxyWdnyy/X7WrdHjdNvpiU1/54H9/d3D8bxhDnx1+u8Jcn/19/CIRmAQ76cvlkXZQzi/ezPjcOgQCzqMQQVuQlEbiLawvpRbW8JSAl39N8lS8hb2/yxaokYM2Xy9fZZT6M2800DCn2+GmRkYlc+BSUTxST1xn17HVBHfhvuP7oT2JXcvmP/p8AAAD//+wuro9nDAAA"; }
        }
    }
}
