// <auto-generated />
namespace migration_rnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedName : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208141302381_AddedName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so0VxUWctYfH718vZR+lxWWSExOu8PH9PjHYeAqOPbF/U2ylh1V6/uV7l3ONnH31x/WZOlPAbUbPfK78OPqCPXtbVKq/b61f5ub56RsjdDd+7233Rvua9g97pt2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mRMZ8tnLrG3zeol3c8ZeqfBo9entCPHw7s4eCHE3Wy6rlinbQ7yDJv41iL5uaxAofVa8y2fP8+VFO7fIfpG9M5/Qrx+lXy0L4ix6qa3XuT84+dvv9PFdNxf9GSJ+abOCKGCmyfDEm7xp8WX+ru3Mmbz4Om/DmW0+Sl1HwkZjM+lRhGzXjkfvCpMaZr47wM2Pv8hWK3Tp3tRP0tfC2ifbr9+fhxcC4+60ibCyxdb2RMyTXeSdb6lrwvRZUTft06zNJhlm72S26DV7H0KbLjv07kqOI795Ab/LS4Gs23npQHB0fEZDW5AU8Ch1jITIgBjru6+nWZnVEUE8qcr1YjkkzJveFvnw35dP+hAe3+2g3qWOJwbasqNSuuTexLLdJrZ3y7odFn2s7HKzVu7xjzT5KCXSXBYz8M7r66bNF2M0GL/+ReVJWdB4XYMvsmVxTlz1pnqbw8Ls7Nz/+trdKrWmmZX/L1XxBUZ/ozLvWYDbq+blZVZP51m9tcje3fkm1W1fWdxK125StcIun300m1SEvqDpVPTXVMR97n181/c8Hj/Nm+LCgYAfssynUDgOqGlztjyvDLFpaD5GpklnLr7I22xGFDqu2+I8m7b09TRvGh7vT2blmpqcLib57Gz55bpdrdvjpskXk/LaH+/ju5v7Z2sT4vz4yxX+8sT16w+B0CxoCPmXyyfropxZvJ/1eXEIBJhFGZywIneBwF1cW0gvquUtASn5nuarfAnxeJMvViUBa75cvs4u82HcbqZhSLHHT4uM7M7Cp6B8opi8zqhnrwvqwH/D9Ud/EruS23v0/wQAAP//8DHQu2sLAAA="; }
        }
    }
}
